home:
    pattern:  /
    defaults:  { _controller: AppBundle:Default:index }

login:
    pattern:   /login
    defaults:  { _controller: AppBundle:Default:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout