# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

services:
    double_password_authenticator:
        class:     AppBundle\Security\DoublePasswordAuthenticator
        arguments: [ "@security.password_encoder", %masterpassword% ]

