# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    user_provider:
        class: AppBundle\Services\UserProvider

    security.authentication.provider:
        class: AppBundle\Security\AuthProvider
        arguments:
            - user_provider # user provider

    security.authentication.listener:
        class: AppBundle\Security\AuthListener
        arguments: ["@security.token_storage", "@security.authentication.manager"]
